services:
  app:
    build: .
    ports:
      - "5000:5000"         # Exposes the server port (5000) to the host
    environment:
      - DATABASE_DIRECTORY=/data/
      - DATABASE_NAME=user_db.db
      - SERVER_HOST=0.0.0.0            # Server is listening on all network interfaces
      - SERVER_PORT=5000
    volumes:
      - dbdata:/data                 # Mounts the shared volume for persistent storage of the database
    depends_on:
      - sqlite

  sqlite:
    image: nouchka/sqlite3:latest      # Uses image that contains SQLite tools
    volumes:
      - dbdata:/data                 # Dataabse shares the same volume with the app service
    command: tail -f /dev/null      # Keeps the container running

volumes:
  dbdata: