operation.succeeded=Operation succeeded
failed.to.find.user=Failed to find user
registration.successful=Registration successful
registration.failed.user.exists=Registration failed: User already exists
user.login.succeeded=User login successful
admin.login.succeeded=Admin login successful
login.failed.incorrect.password=Login failed: Incorrect password
logout.succeeded=Logout succeeded
authorization.succeeded=Authorization succeeded
authorization.failed=Authorization failed
switch.succeeded.admin=Switch succeeded to admin role user
switch.succeeded.nonadmin=Switch succeeded to non-admin role user
switch.failed=Switch failed
role.change.succeeded=Role change succeeded
sending.succeeded=Sending succeeded
sending.failed.box.full=Sending failed: Recipient's mailbox is full
sending.failed.too.long.message=Sending failed: Message too long (maximum 255 characters)
sending.failed.recipient.not.found=Sending failed: Recipient not found
mail.deletion.succeeded=Mails deletion succeeded
mailbox.empty=Mailbox is empty
unknown.request=Unknown request
unknown.response=Unknown response