# Responses
operation.succeeded=Operation completed successfully
unknown.request=Unknown request
failed.to.find.user=User not found
failed.to.find.message=Message not found
registration.successful=Registration successful
registration.failed.user.exists=Registration failed: User already exists
user.login.succeeded=User login successful
admin.login.succeeded=Admin login successful
login.failed.incorrect.password=Login failed: Incorrect password
logout.succeeded=Logout successful
user.switch.succeeded=Switched to account with role USER
admin.switch.succeeded=Switched to account with role ADMIN
user.delete.succeeded=User deletion successful
role.change.succeeded=Role change successful
sending.succeeded=Message sent successfully
sending.failed.box.full=Sending failed: Recipient's mailbox is full
mail.deletion.succeeded=Mail deletion successful
mailbox.empty=Mailbox is empty

# Database configuration
database.username=mail_user
database.port=5432
database.name=mailbox_db
database.password=mail123

# Server configuration
server.host=localhost
server.port=5000

# Elastic search configuration
elastic.host=elasticsearch
elastic.port=9200



