/*
 * This file is generated by jOOQ.
 */
package com.yourpackage.jooq.tables.records;


import com.yourpackage.jooq.tables.Mails;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailsRecord extends UpdatableRecordImpl<MailsRecord> implements Record4<Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mails.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mails.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.mails.sender_id</code>.
     */
    public void setSenderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mails.sender_id</code>.
     */
    public Integer getSenderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.mails.receiver_id</code>.
     */
    public void setReceiverId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mails.receiver_id</code>.
     */
    public Integer getReceiverId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.mails.message</code>.
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mails.message</code>.
     */
    public String getMessage() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Mails.MAILS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Mails.MAILS.SENDER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Mails.MAILS.RECEIVER_ID;
    }

    @Override
    public Field<String> field4() {
        return Mails.MAILS.MESSAGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSenderId();
    }

    @Override
    public Integer component3() {
        return getReceiverId();
    }

    @Override
    public String component4() {
        return getMessage();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSenderId();
    }

    @Override
    public Integer value3() {
        return getReceiverId();
    }

    @Override
    public String value4() {
        return getMessage();
    }

    @Override
    public MailsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MailsRecord value2(Integer value) {
        setSenderId(value);
        return this;
    }

    @Override
    public MailsRecord value3(Integer value) {
        setReceiverId(value);
        return this;
    }

    @Override
    public MailsRecord value4(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public MailsRecord values(Integer value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MailsRecord
     */
    public MailsRecord() {
        super(Mails.MAILS);
    }

    /**
     * Create a detached, initialised MailsRecord
     */
    public MailsRecord(Integer id, Integer senderId, Integer receiverId, String message) {
        super(Mails.MAILS);

        setId(id);
        setSenderId(senderId);
        setReceiverId(receiverId);
        setMessage(message);
        resetChangedOnNotNull();
    }
}
