/*
 * This file is generated by jOOQ.
 */
package com.yourpackage.jooq;


import com.yourpackage.jooq.tables.Mailboxes;
import com.yourpackage.jooq.tables.Mails;
import com.yourpackage.jooq.tables.Users;
import com.yourpackage.jooq.tables.records.MailboxesRecord;
import com.yourpackage.jooq.tables.records.MailsRecord;
import com.yourpackage.jooq.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MailboxesRecord> MAILBOXES_PKEY = Internal.createUniqueKey(Mailboxes.MAILBOXES, DSL.name("mailboxes_pkey"), new TableField[] { Mailboxes.MAILBOXES.ID }, true);
    public static final UniqueKey<MailsRecord> MAILS_PKEY = Internal.createUniqueKey(Mails.MAILS, DSL.name("mails_pkey"), new TableField[] { Mails.MAILS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);
}
