/*
 * This file is generated by jOOQ.
 */
package com.yourpackage.jooq;


import com.yourpackage.jooq.tables.Mailboxes;
import com.yourpackage.jooq.tables.Mails;
import com.yourpackage.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.mailboxes</code>.
     */
    public final Mailboxes MAILBOXES = Mailboxes.MAILBOXES;

    /**
     * The table <code>public.mails</code>.
     */
    public final Mails MAILS = Mails.MAILS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Mailboxes.MAILBOXES,
            Mails.MAILS,
            Users.USERS
        );
    }
}
