/*
 * This file is generated by jOOQ.
 */
package com.yourpackage.jooq;


import com.yourpackage.jooq.tables.Mailboxes;
import com.yourpackage.jooq.tables.Mails;
import com.yourpackage.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.mailboxes</code>.
     */
    public static final Mailboxes MAILBOXES = Mailboxes.MAILBOXES;

    /**
     * The table <code>public.mails</code>.
     */
    public static final Mails MAILS = Mails.MAILS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
