/*
 * This file is generated by jOOQ.
 */
package com.yourpackage.jooq.tables;


import com.yourpackage.jooq.Keys;
import com.yourpackage.jooq.Public;
import com.yourpackage.jooq.tables.records.MailboxesRecord;

import java.util.Collection;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mailboxes extends TableImpl<MailboxesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mailboxes</code>
     */
    public static final Mailboxes MAILBOXES = new Mailboxes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MailboxesRecord> getRecordType() {
        return MailboxesRecord.class;
    }

    /**
     * The column <code>public.mailboxes.id</code>.
     */
    public final TableField<MailboxesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mailboxes.opened</code>.
     */
    public final TableField<MailboxesRecord, String> OPENED = createField(DSL.name("opened"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.mailboxes.unread</code>.
     */
    public final TableField<MailboxesRecord, String> UNREAD = createField(DSL.name("unread"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.mailboxes.sent</code>.
     */
    public final TableField<MailboxesRecord, String> SENT = createField(DSL.name("sent"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Mailboxes(Name alias, Table<MailboxesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Mailboxes(Name alias, Table<MailboxesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mailboxes</code> table reference
     */
    public Mailboxes(String alias) {
        this(DSL.name(alias), MAILBOXES);
    }

    /**
     * Create an aliased <code>public.mailboxes</code> table reference
     */
    public Mailboxes(Name alias) {
        this(alias, MAILBOXES);
    }

    /**
     * Create a <code>public.mailboxes</code> table reference
     */
    public Mailboxes() {
        this(DSL.name("mailboxes"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MailboxesRecord, Integer> getIdentity() {
        return (Identity<MailboxesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MailboxesRecord> getPrimaryKey() {
        return Keys.MAILBOXES_PKEY;
    }

    @Override
    public Mailboxes as(String alias) {
        return new Mailboxes(DSL.name(alias), this);
    }

    @Override
    public Mailboxes as(Name alias) {
        return new Mailboxes(alias, this);
    }

    @Override
    public Mailboxes as(Table<?> alias) {
        return new Mailboxes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Mailboxes rename(String name) {
        return new Mailboxes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mailboxes rename(Name name) {
        return new Mailboxes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mailboxes rename(Table<?> name) {
        return new Mailboxes(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mailboxes where(Condition condition) {
        return new Mailboxes(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mailboxes where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mailboxes where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mailboxes where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mailboxes where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mailboxes where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mailboxes where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mailboxes where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mailboxes whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mailboxes whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
